version: '3'
services:
  app:
    container_name: madams-app
    restart: always
    build: .
    ports:
      - '80:5000'
      - '8731:5000'
    links:
      - mongodb
      - redis
    environment:
      PORT: 5000
      REDIS_HOST: redis
      MONGO_HOST: mongodb:27017/madams-express

  mongodb:
    container_name: madams-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db:/data/db
      - /Users/herlambang/mongo-data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: madams
      MONGO_INITDB_ROOT_PASSWORD: madadadadam173

  redis:
    container_name: madams-redis
    image: redis
    ports:
      - '6379:6379'
