version: '3'
services:
  mongo:
    container_name: madams-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /Users/herlambang/data/db:/data/db
    #   # - /data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: madams
      MONGO_INITDB_ROOT_PASSWORD: madadadadam173

  redis:
    container_name: madams-redis
    image: redis
    ports:
      - '6379:6379'

  app:
    container_name: madams-app
    restart: always
    build: .
    ports:
      - '8000:5000'
      # - '80:5000'
    links:
      - mongo
      - redis
    environment:
      PORT: 5000
      REDIS_HOST: redis
      MONGO_HOST: mongo:27017/madams
      MONGO_USERNAME: madams
      MONGO_PASSWORD: madadadadam173
