version: '3'
services:
  app:
    container_name: madams
    restart: always
    build: .
    ports:
      - '8000:5000'
    links:
      - mongo

  mongo:
    container_name: madams-mongo
    image: mongo
    ports:
      - '27017:27017'

  # redis:
  #   container_name: madams-redis
  #   image: redis
  #   ports:
  #     - '6379:6379'
