version: '3.4'

services:
  mongo:
    container_name: madams-mongo
    image: mongo
    env_file: .env
    networks:
      - madamsnet
    ports:
      - '27017:27017'
    volumes:
      - /data/db:/data/db

  redis:
    container_name: madams-redis
    image: redis
    env_file: .env
    networks:
      - madamsnet
    ports:
      - '6379:6379'

  app:
    container_name: madams-app
    restart: always
    env_file: .env
    build: .
    ports:
      - '80:5000'
    networks:
      - madamsnet

networks:
  madamsnet:
